# SPDX-License-Identifier: Apache-2.0
#
# Houdini  A container escape artist
# Copyright (c) 2022  William Findlay
#
# February 25, 2022  William Findlay  Created this.
#

[package]
name = "houdini"
version = "0.1.0"
edition = "2021"
authors = ["William Findlay <william@williamfindlay.com>"]
description = """A container escape artist"""

[[bin]]
name = "houdini"
path = "bin/houdini.rs"

[lib]
name = "houdini"
path = "src/lib.rs"

[dependencies]
anyhow = "1.0.55"
atty = "0.2.14"
clap = "3.1.2"
clap_derive = "3.1.2"
docker-api = "0.8.0"
human-panic = "1.0.3"
jwalk = "0.6.0"
log-panics = { version = "2.0.0", features = ["with-backtrace"] }
tokio = "1.17.0"
tracing = "0.1.31"
tracing-log = "0.1.2"
tracing-subscriber = { version = "0.3.9", features = ["fmt", "std", "json"] }

[features]
